CREATE TABLE `user` (
	`user_id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`id` VARCHAR(20) NOT NULL UNIQUE,
	`email` VARCHAR(50) NOT NULL UNIQUE,
	`pwd` VARCHAR(100) NOT NULL,
	`name` VARCHAR(20) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `calendar` (
	`calendar_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`user_id` BIGINT NOT NULL,
	`title` VARCHAR(20) NOT NULL,
	`color` VARCHAR(15) NOT NULL DEFAULT '#FF922B',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`user_id`) REFERENCES user (`user_id`)  ON DELETE CASCADE
);

CREATE TABLE `board` (
	`board_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`calendar_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	`title` VARCHAR(20) NOT NULL,
	`content` VARCHAR(1000) NOT NULL,
	`state` INT NOT NULL DEFAULT 1,
	`start_day` DATE NOT NULL,
	`d_day` DATE NOT NULL,
	`dead_line` TIME NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`user_id`) REFERENCES user (`user_id`)  ON DELETE CASCADE,
	FOREIGN KEY (`calendar_id`) REFERENCES calendar (`calendar_id`)  ON DELETE CASCADE
);

CREATE TABLE tag (
   tag_id BIGINT  AUTO_INCREMENT PRIMARY KEY,
   calendar_id BIGINT NOT NULL,
   title VARCHAR(20) NOT NULL,
   color INT NOT NULL DEFAULT 1,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (calendar_id) REFERENCES calendar (calendar_id)  ON DELETE CASCADE,
   UNIQUE (calendar_id, title)
);

CREATE TABLE `comment` (
	`comment_id`	BIGINT PRIMARY KEY AUTO_INCREMENT,
	`board_id`	BIGINT NOT NULL,
	`user_id`	BIGINT 	NOT NULL,
	`content`	VARCHAR(100) NOT NULL,
	`created_at`	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at`  DATETIME  DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (board_id) REFERENCES board (board_id) ON DELETE CASCADE ,
	FOREIGN KEY (user_id) REFERENCES user (user_id)  ON DELETE CASCADE
);

CREATE TABLE `file` (
	file_id  BIGINT PRIMARY KEY AUTO_INCREMENT,
	file_name VARCHAR(100) NOT NULL UNIQUE,
	board_id BIGINT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (board_id) REFERENCES board (board_id)  ON DELETE CASCADE
);

CREATE TABLE `notice` (
	`notice_id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`calendar_id` BIGINT NOT NULL,
	`content` VARCHAR(500) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (calendar_id) REFERENCES calendar (calendar_id)  ON DELETE CASCADE
 );

CREATE TABLE `notice_list` (
	`notice_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	updated_at DATETIME,
	PRIMARY KEY(notice_id, user_id),
	FOREIGN KEY (notice_id) REFERENCES notice (notice_id)  ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES user (user_id)  ON DELETE CASCADE
);

CREATE TABLE calendar_user (
	user_id BIGINT NOT NULL,
	calendar_id BIGINT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (user_id, calendar_id),
	FOREIGN KEY (user_id) REFERENCES user (user_id)  ON DELETE CASCADE,
	FOREIGN KEY (calendar_id) REFERENCES calendar (calendar_id)  ON DELETE CASCADE
);

CREATE TABLE board_tag (
	board_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (board_id, tag_id),
	FOREIGN KEY (board_id) REFERENCES board (board_id)  ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES tag (tag_id)  ON DELETE CASCADE
);