spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/db_odd_first_3
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: postime9@gmail.com
    password: exdw trep jtec xlew
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
  cache:
    disabled: true

file:
  dir: D:\youp\download\todo\

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_3
    username: odd_first_3
    password: loctite
file:
  dir: /home/download/postime/
